package com.yzx.module_common.model

data class Track(
    val a: Any,
    val al: PlayListAlblum,
    val alia: List<Any>,
    val ar: List<PlayListSinger>,
    val cd: String,
    val cf: String,
    val copyright: Long,
    val cp: Long,
    val crbt: Any,
    val djId: Long,
    val dt: Long,
    val fee: Long,
    val ftype: Long,
    val id: Long,
    val mark: Long,
    val mst: Long,
    val mv: Long,
    val name: String,
    val no: Long,
    val noCopyrightRcmd: Any,
    val originCoverType: Long,
    val pop: Long,
    val pst: Long,
    val publishTime: Long,
    val rt: String,
    val rtUrl: Any,
    val rtUrls: List<Any>,
    val rtype: Long,
    val rurl: Any,
    val s_id: Long,
    val st: Long,
    val t: Long,
    val v: Long,
    var url: String
)